name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
         CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
         JACOCO_SOURCE_PATH: "/home/runner/work/SQUA/src"
        with:
          coverageCommand: mvn test -f /home/runner/work/SQUA/pom.xml
          coverageLocations: /home/runner/work/SQUA/target/site/jacoco/jacoco.xml:jacoco