name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
         CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
         JACOCO_SOURCE_PATH: "${{github.workspace}}/src"
         with:
             # The report file must be there, otherwise Code Climate won't find it
            coverageCommand: mvn test
            coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco