name: Build&Test Linux
on: [push]
jobs:
    build:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - run: mvn --batch-mode --update-snapshots verify